/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Wasmd } from './Wasmd';
export * as factories from './factories';
export { Wasmd__factory } from './factories/Wasmd__factory';
